---
- name: Install the infrastructure
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "/usr/bin/python3"
  gather_facts: true
  become: false
  roles:
    - { role: infrastructure/terraform, tags: infrastructure }

- name: Configure /etc/hosts
  hosts:
    - control
    - masters
    - workers
  gather_facts: true
  become: true
  roles:
    - { role: infrastructure/hostsfile, tags: infrastructure }
