---
kubeadmin_config: /etc/kubernetes/admin.conf

# The ip address of the first master node is
# used to bootstrap a new cluster
first_master_node_ip_address: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4'].address | default(groups['masters'][0]) }}"

# Extent kubeadm options when Cilium is used
extended_kubeadm_opts: "{{ (network_plugin == 'cilium') | ternary(kubeadm_opts + ' --skip-phases=addon/kube-proxy', kubeadm_opts) }}"

cilium_helm_values:
  externalIPs:
    enabled: true
  hostPort:
    enabled: true
  kubeProxyReplacement: true
  k8sServiceHost: "{{ ansible_facts['default_ipv4']['address'] }}"
  k8sServicePort: 6443
  loadBalancer:
    algorithm: maglev
  nodeinit:
    enabled: true
  nodePort:
    enabled: true
  operator:
    replicas: 1
  bgp:
    enabled: "{{ cilium_enable_bgp | bool }}"
    announce:
      loadbalancerIP: true
  hubble:
    enabled: "{{ install_hubble | bool }}"
    metrics:
      enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - http
    listenAddress: ":4244"
    relay:
      enabled: true
    ui:
      enabled: true
