---
# Install/configure the requirements needed by kubeadm/kubernetes

- name: Kubernetes YUM repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: "Kubernetes YUM repo"
    baseurl: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_installation_version }}/rpm/"
    gpgkey: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_installation_version }}/rpm/repodata/repomd.xml.key"
    gpgcheck: true
    repo_gpgcheck: true

- name: Install required packages for Kubernetes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "kubelet-{{ rpm_version }}"
    - "kubeadm-{{ rpm_version }}"
    - iproute-tc

- name: Kubernetes sysctl settings
  ansible.posix.sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
  loop:
    - { name: 'net.ipv4.ip_forward', value: 1 }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: 1 }

- name: Run the kubelet service
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
