---
- name: Configure CRI-O repository
  yum_repository:
    name: crio
    description: CRI-O YUM repo
    baseurl: "https://pkgs.k8s.io/addons:/cri-o:/{{ _project_path }}/rpm/"
    gpgkey: "https://pkgs.k8s.io/addons:/cri-o:/{{ _project_path }}/rpm/repodata/repomd.xml.key"
    gpgcheck: yes
  vars:
    _project_path: 'prerelease:/main'

- name: Load kernel modules needed by CRI-O
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - "overlay"
    - "br_netfilter"

- name: Install CRI-O
  package:
    name: cri-o
    state: present

# - name: Configure /etc/sysconfig/kubelet
#   copy:
#     content: "KUBELET_EXTRA_ARGS=--runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice --cgroup-driver=systemd\n"
#     dest: /etc/sysconfig/kubelet
#   notify: restart kubelet

- name: Configure /etc/crictl.yaml
  copy:
    content: "runtime-endpoint: unix:///var/run/crio/crio.sock"
    dest: /etc/crictl.yaml
  notify: restart crio

- name: Service CRI-O
  service:
    name: crio
    state: started
    enabled: true
