---
- name: Configure CRI-O repository
  yum_repository:
    name: crio
    description: CRI-O YUM repo
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ ansible_distribution }}_{{ _major_version }}/
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ ansible_distribution }}_{{ _major_version }}/repodata/repomd.xml.key
    gpgcheck: yes
  vars:
    # A CentOS 8 version for the the Yum repo does not exist, the Centos 7 RPM is also suitable for Centos 8
    _major_version: "{{ (ansible_distribution_major_version|int == 8) | ternary('7', ansible_distribution_major_version) }}"

- name: Configure libcontainers repository
  yum_repository:
    name: libcontainers
    description: Libcontainers YUM repo
    baseurl: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ ansible_distribution }}_{{ _major_version }}/
    gpgkey: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ ansible_distribution }}_{{ _major_version }}/repodata/repomd.xml.key
    gpgcheck: yes
  vars:
    # A CentOS 8 version for the the Yum repo does not exist, the Centos 7 RPM is also suitable for Centos 8
    _major_version: "{{ (ansible_distribution_major_version|int == 8) | ternary('7', ansible_distribution_major_version) }}"

- name: Load kernel modules needed by CRI-O
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - "overlay"
    - "br_netfilter"

- name: Install CRI-O
  package:
    name: cri-o
    state: present

- name: Configure /etc/sysconfig/kubelet
  copy:
    content: "KUBELET_EXTRA_ARGS=--runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice --cgroup-driver=systemd\n"
    dest: /etc/sysconfig/kubelet
  notify: restart kubelet

- name: Configure /etc/crictl.yaml
  copy:
    content: "runtime-endpoint: unix:///var/run/crio/crio.sock\ncgroup-manager: systemd\n"
    dest: /etc/crictl.yaml
  notify: restart crio

- name: Service CRI-O
  service:
    name: crio
    state: started
    enabled: true
