---
- name: Configure CRI-O repository
  ansible.builtin.yum_repository:
    name: crio
    description: CRI-O YUM repo
    baseurl: "https://pkgs.k8s.io/addons:/cri-o:/{{ _project_path }}/rpm/"
    gpgkey: "https://pkgs.k8s.io/addons:/cri-o:/{{ _project_path }}/rpm/repodata/repomd.xml.key"
    gpgcheck: yes
  vars:
    _project_path: 'prerelease:/main'

- name: Load kernel modules needed by CRI-O
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - "overlay"
    - "br_netfilter"

- name: Install CRI-O
  ansible.builtin.package:
    name: cri-o
    state: present

- name: Configure /etc/crictl.yaml
  ansible.builtin.copy:
    content: "runtime-endpoint: unix:///var/run/crio/crio.sock"
    dest: /etc/crictl.yaml
  notify: Restart crio

- name: Service CRI-O
  ansible.builtin.service:
    name: crio
    state: started
    enabled: true
