---
# Install the Docker runtime

- name: Docker YUM repository
  yum_repository:
    name: docker-ce-stable
    description: 'Docker CE Stable - $basearch'
    baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install required packages for the Docker runtime
  package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - iptables

- name: Run the docker service
  service:
    name: docker
    state: started
    enabled: true
