---
# Make 1.17.3-0 from v1.17.3
rpm_version: "{{ kubernetes_version | regex_replace('^v', '') }}-0"
crio_version: "{{ kubernetes_version | regex_replace('^v([0-9]+)\\.([0-9]+)\\.[0-9]+', '\\1.\\2') }}"