---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --kubernetes-version {{ kubernetes_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ apiserver_advertise_address }} \
                 --node-name {{ ansible_hostname }} \
                 --skip-phases "addon/kube-proxy" \
                 {{ extended_kubeadm_opts }}
  register: init_cluster
  
