---
# https://github.com/cilium/cilium/issues/10645
# https://docs.cilium.io/en/v1.8/operations/system_requirements/
# echo 'net.ipv4.conf.lxc*.rp_filter = 0' > /etc/sysctl.d/99-override_cilium_rp_filter.conf
# systemctl restart systemd-sysctl

- name: Add Cilium Helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io
  tags:
    - cilium
    - network
    - master

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_release }}"
    release_namespace: kube-system
    release_values: "{{ cilium_helm_values }}"
  tags:
    - cilium
    - network
    - master

- name: Configure BPG ConfigMap
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: bgp-config
        namespace: kube-system
      data:
        config.yaml: |
          peers:
            - peer-address: 192.168.1.1
              peer-asn: 64512
              my-asn: 64512
          address-pools:
            - name: default
              protocol: bgp
              addresses:
                - 172.16.10.0/24
  when: (cilium_enable_bgp | bool)
  tags:
    - cilium
    - network
    - master
